import Header from "@/components/Header";
import Footer from "@/components/Footer";
//import the font
import { Roboto_Mono } from "next/font/google";

import "./globals.css";
//we need to configure our font with different properties
const roboto = Roboto_Mono({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* apply the font */}
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
